### ISSUE TITLE
python3.5导包错误

### ISSUE THREAD

**Issue by Nimeizi** [SinoReimu/singleNet_Windows#1]
ImportError: No module named 'ConfigParser'

**Comment by SinoReimu** [comment]
用pip安装过么 我有空加个依赖安装进去

**Comment by Nimeizi** [comment]
3.2以上好像是 用 configparser 这个包名

**Comment by SinoReimu** [comment]
我的readme写错了 这个是在python 2.7下写的 改下包名和对应的方法应该就好了
